import django.contrib.admin 
from django.contrib import admin

# Register your models here.
from library.models  import Author, Book, BookInstance, Genre, Question, Answer
# Generated by Django 5.0.3 on 2024-04-01 14:35


a = Answer(question_id=1, text='blabla') # ссылка по id
a.save()
